"""Essential Eight assessment content. Requirement text was extracted from ASD's published tables.

Requirement wording is from the Australian Signals Directorate's Essential Eight Maturity Model
(November 2023), https://www.cyber.gov.au/, licensed under Creative Commons Attribution 4.0
International (https://creativecommons.org/licenses/by/4.0/). Titles, effort tags, strategy
summaries and priorities are EightGuard's own additions and are not endorsed by ASD.

Each maturity level's appendix restates the levels below it. Here every requirement appears once,
tagged with the level that introduces it; `until` marks the few that a stricter requirement
replaces at the next level. Requirements worded identically under several strategies (asset
discovery, logging, incident handling) share an answer `key`, so they're answered once.

Answers are stored by `key`, so keys must never change within a content VERSION. A new ASD
release gets a new VERSION; snapshots record the version they were scored against.
"""

from dataclasses import dataclass

VERSION = "e8mm-2023-11"
ATTRIBUTION = (
    "Requirements © Commonwealth of Australia (Australian Signals Directorate), "
    "Essential Eight Maturity Model (November 2023), CC BY 4.0. Plain-English titles, effort "
    "and priorities by EightGuard."
)
SOURCE_URL = "https://www.cyber.gov.au/business-government/asds-cyber-security-frameworks/essential-eight/essential-eight-maturity-model"
LICENCE_URL = "https://creativecommons.org/licenses/by/4.0/"
MAX_LEVEL = 3


@dataclass(frozen=True)
class Strategy:
    code: str
    name: str
    priority: int  # EightGuard's suggested order of work for a small business (1 = first)
    summary: str


@dataclass(frozen=True)
class Requirement:
    id: str
    strategy: str
    level: int  # the maturity level that introduces it
    until: int | None  # last level it applies to; None = applies up to Maturity Level Three
    key: str  # answer key (shared by identically worded requirements)
    effort: str  # low | medium | high
    title: str
    text: str  # ASD's wording

    def applies_at(self, level: int) -> bool:
        return self.level <= level <= (self.until or MAX_LEVEL)


# Listed in ASD's order
STRATEGIES = (
    Strategy("PA", "Patch applications", 2,
             "Attackers use known flaws in apps like browsers, Office and PDF readers within days "
             "of a fix being released. Keeping apps patched closes those doors."),
    Strategy("PO", "Patch operating systems", 3,
             "Unpatched Windows, macOS, servers and network devices are one of the most common ways "
             "in. Patch quickly, and replace systems that no longer get updates."),
    Strategy("MFA", "Multi-factor authentication", 1,
             "Stolen passwords are the easiest way into email and cloud accounts. A second factor, "
             "ideally a passkey or security key, stops most of these attacks."),
    Strategy("RAP", "Restrict administrative privileges", 5,
             "Admin accounts can change anything, so attackers hunt for them. Keep them few, "
             "separate from everyday accounts and away from email and the web."),
    Strategy("AC", "Application control", 8,
             "Only letting approved software run stops most malware and ransomware from starting, "
             "even if someone opens a malicious attachment."),
    Strategy("MAC", "Restrict Microsoft Office macros", 6,
             "Macros in Office documents are a classic way to deliver malware. Most staff never "
             "need them, so turn them off and tightly control the rest."),
    Strategy("UAH", "User application hardening", 7,
             "Browsers, Office and PDF readers have risky features attackers abuse. Switching those "
             "off and locking the settings shrinks what an attacker can do."),
    Strategy("BAK", "Regular backups", 4,
             "Backups are how you recover from ransomware, mistakes and hardware failure, but only "
             "if they're tested, protected and can't be deleted by an attacker."),
)

REQUIREMENTS = (
    Requirement("PA-1.01", "PA", 1, None, "ASSET-DISCOVERY", "medium",
                "Find all devices and services automatically, at least fortnightly",
                "An automated method of asset discovery is used at least fortnightly to support the detection of assets for subsequent vulnerability scanning activities."),
    Requirement("PA-1.02", "PA", 1, None, "VULN-SCANNER", "medium",
                "Use a vulnerability scanner with an up-to-date database",
                "A vulnerability scanner with an up-to-date vulnerability database is used for vulnerability scanning activities."),
    Requirement("PA-1.03", "PA", 1, None, "PA-1.03", "medium",
                "Scan online services for missing patches daily",
                "A vulnerability scanner is used at least daily to identify missing patches or updates for vulnerabilities in online services."),
    Requirement("PA-1.04", "PA", 1, None, "PA-1.04", "medium",
                "Scan Office, browsers, email, PDF and security software for missing patches weekly",
                "A vulnerability scanner is used at least weekly to identify missing patches or updates for vulnerabilities in office productivity suites, web browsers and their extensions, email clients, PDF software, and security products."),
    Requirement("PA-1.05", "PA", 1, None, "PA-1.05", "medium",
                "Patch critical or exploited flaws in online services within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in online services are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PA-1.06", "PA", 1, None, "PA-1.06", "low",
                "Patch other flaws in online services within two weeks",
                "Patches, updates or other vendor mitigations for vulnerabilities in online services are applied within two weeks of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PA-1.07", "PA", 1, 2, "PA-1.07", "low",
                "Patch Office, browsers, email, PDF and security software within two weeks",
                "Patches, updates or other vendor mitigations for vulnerabilities in office productivity suites, web browsers and their extensions, email clients, PDF software, and security products are applied within two weeks of release."),
    Requirement("PA-1.08", "PA", 1, None, "PA-1.08", "medium",
                "Remove online services the vendor no longer supports",
                "Online services that are no longer supported by vendors are removed."),
    Requirement("PA-1.09", "PA", 1, None, "PA-1.09", "low",
                "Remove unsupported Office, browser, email, PDF, Flash and security software",
                "Office productivity suites, web browsers and their extensions, email clients, PDF software, Adobe Flash Player, and security products that are no longer supported by vendors are removed."),
    Requirement("PA-2.01", "PA", 2, None, "PA-2.01", "medium",
                "Scan all other applications for missing patches fortnightly",
                "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in applications other than office productivity suites, web browsers and their extensions, email clients, PDF software, and security products."),
    Requirement("PA-2.02", "PA", 2, None, "PA-2.02", "medium",
                "Patch all other applications within one month",
                "Patches, updates or other vendor mitigations for vulnerabilities in applications other than office productivity suites, web browsers and their extensions, email clients, PDF software, and security products are applied within one month of release."),
    Requirement("PA-3.01", "PA", 3, None, "PA-3.01", "medium",
                "Patch critical or exploited flaws in Office, browsers, email, PDF and security software within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in office productivity suites, web browsers and their extensions, email clients, PDF software, and security products are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PA-3.02", "PA", 3, None, "PA-3.02", "low",
                "Patch other flaws in Office, browsers, email, PDF and security software within two weeks",
                "Patches, updates or other vendor mitigations for vulnerabilities in office productivity suites, web browsers and their extensions, email clients, PDF software, and security products are applied within two weeks of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PA-3.03", "PA", 3, None, "PA-3.03", "medium",
                "Remove any other application the vendor no longer supports",
                "Applications other than office productivity suites, web browsers and their extensions, email clients, PDF software, Adobe Flash Player, and security products that are no longer supported by vendors are removed."),
    Requirement("PO-1.01", "PO", 1, None, "ASSET-DISCOVERY", "medium",
                "Find all devices and services automatically, at least fortnightly",
                "An automated method of asset discovery is used at least fortnightly to support the detection of assets for subsequent vulnerability scanning activities."),
    Requirement("PO-1.02", "PO", 1, None, "VULN-SCANNER", "medium",
                "Use a vulnerability scanner with an up-to-date database",
                "A vulnerability scanner with an up-to-date vulnerability database is used for vulnerability scanning activities."),
    Requirement("PO-1.03", "PO", 1, None, "PO-1.03", "medium",
                "Scan internet-facing servers and network devices for missing OS patches daily",
                "A vulnerability scanner is used at least daily to identify missing patches or updates for vulnerabilities in operating systems of internet-facing servers and internet-facing network devices."),
    Requirement("PO-1.04", "PO", 1, None, "PO-1.04", "medium",
                "Scan computers, internal servers and network devices for missing OS patches fortnightly",
                "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in operating systems of workstations, non-internet-facing servers and non-internet-facing network devices."),
    Requirement("PO-1.05", "PO", 1, None, "PO-1.05", "medium",
                "Patch critical or exploited OS flaws on internet-facing systems within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in operating systems of internet-facing servers and internet-facing network devices are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PO-1.06", "PO", 1, None, "PO-1.06", "low",
                "Patch other OS flaws on internet-facing systems within two weeks",
                "Patches, updates or other vendor mitigations for vulnerabilities in operating systems of internet-facing servers and internet-facing network devices are applied within two weeks of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PO-1.07", "PO", 1, 2, "PO-1.07", "low",
                "Patch computers, internal servers and network devices within one month",
                "Patches, updates or other vendor mitigations for vulnerabilities in operating systems of workstations, non-internet-facing servers and non-internet-facing network devices are applied within one month of release."),
    Requirement("PO-1.08", "PO", 1, None, "PO-1.08", "high",
                "Replace operating systems the vendor no longer supports",
                "Operating systems that are no longer supported by vendors are replaced."),
    Requirement("PO-3.01", "PO", 3, None, "PO-3.01", "medium",
                "Scan drivers for missing patches fortnightly",
                "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in drivers."),
    Requirement("PO-3.02", "PO", 3, None, "PO-3.02", "medium",
                "Scan firmware for missing patches fortnightly",
                "A vulnerability scanner is used at least fortnightly to identify missing patches or updates for vulnerabilities in firmware."),
    Requirement("PO-3.03", "PO", 3, None, "PO-3.03", "medium",
                "Patch critical or exploited OS flaws on computers and internal systems within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in operating systems of workstations, non-internet-facing servers and non-internet-facing network devices are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PO-3.04", "PO", 3, None, "PO-3.04", "low",
                "Patch other OS flaws on computers and internal systems within one month",
                "Patches, updates or other vendor mitigations for vulnerabilities in operating systems of workstations, non-internet-facing servers and non-internet-facing network devices are applied within one month of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PO-3.05", "PO", 3, None, "PO-3.05", "medium",
                "Patch critical or exploited driver flaws within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in drivers are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PO-3.06", "PO", 3, None, "PO-3.06", "medium",
                "Patch other driver flaws within one month",
                "Patches, updates or other vendor mitigations for vulnerabilities in drivers are applied within one month of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PO-3.07", "PO", 3, None, "PO-3.07", "high",
                "Patch critical or exploited firmware flaws within 48 hours",
                "Patches, updates or other vendor mitigations for vulnerabilities in firmware are applied within 48 hours of release when vulnerabilities are assessed as critical by vendors or when working exploits exist."),
    Requirement("PO-3.08", "PO", 3, None, "PO-3.08", "medium",
                "Patch other firmware flaws within one month",
                "Patches, updates or other vendor mitigations for vulnerabilities in firmware are applied within one month of release when vulnerabilities are assessed as non-critical by vendors and no working exploits exist."),
    Requirement("PO-3.09", "PO", 3, None, "PO-3.09", "medium",
                "Run the latest or previous release of each operating system",
                "The latest release, or the previous release, of operating systems are used."),
    Requirement("MFA-1.01", "MFA", 1, None, "MFA-1.01", "medium",
                "Require MFA for your own online services that hold sensitive data",
                "Multi-factor authentication is used to authenticate users to their organisation’s online services that process, store or communicate their organisation’s sensitive data."),
    Requirement("MFA-1.02", "MFA", 1, None, "MFA-1.02", "low",
                "Require MFA for third-party online services that hold your sensitive data",
                "Multi-factor authentication is used to authenticate users to third-party online services that process, store or communicate their organisation’s sensitive data."),
    Requirement("MFA-1.03", "MFA", 1, None, "MFA-1.03", "low",
                "Turn on MFA (where offered) for third-party services holding non-sensitive data",
                "Multi-factor authentication (where available) is used to authenticate users to third-party online services that process, store or communicate their organisation’s non-sensitive data."),
    Requirement("MFA-1.04", "MFA", 1, None, "MFA-1.04", "medium",
                "Require MFA for staff using your customer-facing services with sensitive customer data",
                "Multi-factor authentication is used to authenticate users to their organisation’s online customer services that process, store or communicate their organisation’s sensitive customer data."),
    Requirement("MFA-1.05", "MFA", 1, None, "MFA-1.05", "low",
                "Require MFA for staff using third-party customer services with sensitive customer data",
                "Multi-factor authentication is used to authenticate users to third-party online customer services that process, store or communicate their organisation’s sensitive customer data."),
    Requirement("MFA-1.06", "MFA", 1, None, "MFA-1.06", "medium",
                "Require MFA for customers of services holding their sensitive data",
                "Multi-factor authentication is used to authenticate customers to online customer services that process, store or communicate sensitive customer data."),
    Requirement("MFA-1.07", "MFA", 1, None, "MFA-1.07", "low",
                "Make MFA use something you have (phone, key) plus something you know or are",
                "Multi-factor authentication uses either: something users have and something users know, or something users have that is unlocked by something users know or are."),
    Requirement("MFA-2.01", "MFA", 2, None, "MFA-2.01", "medium",
                "Require MFA for administrators of your systems",
                "Multi-factor authentication is used to authenticate privileged users of systems."),
    Requirement("MFA-2.02", "MFA", 2, None, "MFA-2.02", "medium",
                "Require MFA for all other users of your systems",
                "Multi-factor authentication is used to authenticate unprivileged users of systems."),
    Requirement("MFA-2.03", "MFA", 2, None, "MFA-2.03", "medium",
                "Use phishing-resistant MFA (passkeys, security keys) for online services",
                "Multi-factor authentication used for authenticating users of online services is phishing-resistant."),
    Requirement("MFA-2.04", "MFA", 2, 2, "MFA-2.04", "medium",
                "Offer customers a phishing-resistant MFA option",
                "Multi-factor authentication used for authenticating customers of online customer services provides a phishing-resistant option."),
    Requirement("MFA-2.05", "MFA", 2, None, "MFA-2.05", "medium",
                "Use phishing-resistant MFA for your own systems",
                "Multi-factor authentication used for authenticating users of systems is phishing-resistant."),
    Requirement("MFA-2.06", "MFA", 2, None, "MFA-2.06", "medium",
                "Collect MFA sign-in successes and failures in one central log",
                "Successful and unsuccessful multi-factor authentication events are centrally logged."),
    Requirement("MFA-2.07", "MFA", 2, None, "LOGS-PROTECTED", "medium",
                "Protect event logs from being changed or deleted",
                "Event logs are protected from unauthorised modification and deletion."),
    Requirement("MFA-2.08", "MFA", 2, None, "LOGS-INTERNET-SERVERS", "high",
                "Review logs from internet-facing servers promptly",
                "Event logs from internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("MFA-2.09", "MFA", 2, None, "EVENTS-TRIAGED", "high",
                "Check security events promptly to spot incidents",
                "Cyber security events are analysed in a timely manner to identify cyber security incidents."),
    Requirement("MFA-2.10", "MFA", 2, None, "INCIDENTS-TO-LEAD", "low",
                "Report incidents to your security lead straight away",
                "Cyber security incidents are reported to the chief information security officer, or one of their delegates, as soon as possible after they occur or are discovered."),
    Requirement("MFA-2.11", "MFA", 2, None, "INCIDENTS-TO-ASD", "low",
                "Report incidents to ASD (cyber.gov.au / 1300 CYBER1)",
                "Cyber security incidents are reported to ASD as soon as possible after they occur or are discovered."),
    Requirement("MFA-2.12", "MFA", 2, None, "IR-PLAN-ENACTED", "medium",
                "Follow your incident response plan when an incident happens",
                "Following the identification of a cyber security incident, the cyber security incident response plan is enacted."),
    Requirement("MFA-3.01", "MFA", 3, None, "MFA-3.01", "medium",
                "Require MFA for data repositories (file shares, databases, document stores)",
                "Multi-factor authentication is used to authenticate users of data repositories."),
    Requirement("MFA-3.02", "MFA", 3, None, "MFA-3.02", "high",
                "Require phishing-resistant MFA for customers",
                "Multi-factor authentication used for authenticating customers of online customer services is phishing-resistant."),
    Requirement("MFA-3.03", "MFA", 3, None, "MFA-3.03", "medium",
                "Require phishing-resistant MFA for data repositories",
                "Multi-factor authentication used for authenticating users of data repositories is phishing-resistant."),
    Requirement("MFA-3.04", "MFA", 3, None, "LOGS-INTERNAL-SERVERS", "high",
                "Review logs from internal servers promptly",
                "Event logs from non-internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("MFA-3.05", "MFA", 3, None, "LOGS-WORKSTATIONS", "high",
                "Review logs from staff computers promptly",
                "Event logs from workstations are analysed in a timely manner to detect cyber security events."),
    Requirement("RAP-1.01", "RAP", 1, None, "RAP-1.01", "low",
                "Approve admin access requests before granting them",
                "Requests for privileged access to systems, applications and data repositories are validated when first requested."),
    Requirement("RAP-1.02", "RAP", 1, None, "RAP-1.02", "low",
                "Give admins a separate account used only for admin work",
                "Privileged users are assigned a dedicated privileged user account to be used solely for duties requiring privileged access."),
    Requirement("RAP-1.03", "RAP", 1, None, "RAP-1.03", "medium",
                "Block admin accounts from web browsing and email",
                "Privileged user accounts (excluding those explicitly authorised to access online services) are prevented from accessing the internet, email and web services."),
    Requirement("RAP-1.04", "RAP", 1, None, "RAP-1.04", "medium",
                "Limit admin accounts that need online services to only what they need",
                "Privileged user accounts explicitly authorised to access online services are strictly limited to only what is required for users and services to undertake their duties."),
    Requirement("RAP-1.05", "RAP", 1, None, "RAP-1.05", "high",
                "Keep admin work on a separate environment from everyday work",
                "Privileged users use separate privileged and unprivileged operating environments."),
    Requirement("RAP-1.06", "RAP", 1, None, "RAP-1.06", "medium",
                "Stop normal accounts signing in to admin environments",
                "Unprivileged user accounts cannot logon to privileged operating environments."),
    Requirement("RAP-1.07", "RAP", 1, None, "RAP-1.07", "medium",
                "Stop admin accounts signing in to everyday environments",
                "Privileged user accounts (excluding local administrator accounts) cannot logon to unprivileged operating environments."),
    Requirement("RAP-2.01", "RAP", 2, None, "RAP-2.01", "low",
                "Remove admin access after 12 months unless re-approved",
                "Privileged access to systems, applications and data repositories is disabled after 12 months unless revalidated."),
    Requirement("RAP-2.02", "RAP", 2, None, "RAP-2.02", "low",
                "Disable admin access after 45 days of inactivity",
                "Privileged access to systems and applications is disabled after 45 days of inactivity."),
    Requirement("RAP-2.03", "RAP", 2, None, "RAP-2.03", "medium",
                "Don't run the admin environment as a VM inside an everyday one",
                "Privileged operating environments are not virtualised within unprivileged operating environments."),
    Requirement("RAP-2.04", "RAP", 2, None, "RAP-2.04", "high",
                "Do admin work through jump servers",
                "Administrative activities are conducted through jump servers."),
    Requirement("RAP-2.05", "RAP", 2, None, "RAP-2.05", "medium",
                "Use long, unique, managed passwords for break-glass, local admin and service accounts",
                "Credentials for break glass accounts, local administrator accounts and service accounts are long, unique, unpredictable and managed."),
    Requirement("RAP-2.06", "RAP", 2, None, "RAP-2.06", "medium",
                "Centrally log use of admin access",
                "Privileged access events are centrally logged."),
    Requirement("RAP-2.07", "RAP", 2, None, "RAP-2.07", "medium",
                "Centrally log changes to admin accounts and security groups",
                "Privileged user account and security group management events are centrally logged."),
    Requirement("RAP-2.08", "RAP", 2, None, "LOGS-PROTECTED", "medium",
                "Protect event logs from being changed or deleted",
                "Event logs are protected from unauthorised modification and deletion."),
    Requirement("RAP-2.09", "RAP", 2, None, "LOGS-INTERNET-SERVERS", "high",
                "Review logs from internet-facing servers promptly",
                "Event logs from internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("RAP-2.10", "RAP", 2, None, "EVENTS-TRIAGED", "high",
                "Check security events promptly to spot incidents",
                "Cyber security events are analysed in a timely manner to identify cyber security incidents."),
    Requirement("RAP-2.11", "RAP", 2, None, "INCIDENTS-TO-LEAD", "low",
                "Report incidents to your security lead straight away",
                "Cyber security incidents are reported to the chief information security officer, or one of their delegates, as soon as possible after they occur or are discovered."),
    Requirement("RAP-2.12", "RAP", 2, None, "INCIDENTS-TO-ASD", "low",
                "Report incidents to ASD (cyber.gov.au / 1300 CYBER1)",
                "Cyber security incidents are reported to ASD as soon as possible after they occur or are discovered."),
    Requirement("RAP-2.13", "RAP", 2, None, "IR-PLAN-ENACTED", "medium",
                "Follow your incident response plan when an incident happens",
                "Following the identification of a cyber security incident, the cyber security incident response plan is enacted."),
    Requirement("RAP-3.01", "RAP", 3, None, "RAP-3.01", "medium",
                "Limit admin access to only what each person or service needs",
                "Privileged access to systems, applications and data repositories is limited to only what is required for users and services to undertake their duties."),
    Requirement("RAP-3.02", "RAP", 3, None, "RAP-3.02", "high",
                "Use dedicated secure admin workstations",
                "Secure Admin Workstations are used in the performance of administrative activities."),
    Requirement("RAP-3.03", "RAP", 3, None, "RAP-3.03", "high",
                "Grant admin rights just-in-time, only when needed",
                "Just-in-time administration is used for administering systems and applications."),
    Requirement("RAP-3.04", "RAP", 3, None, "RAP-3.04", "low",
                "Turn on Windows memory integrity",
                "Memory integrity functionality is enabled."),
    Requirement("RAP-3.05", "RAP", 3, None, "RAP-3.05", "low",
                "Turn on Windows Local Security Authority (LSA) protection",
                "Local Security Authority protection functionality is enabled."),
    Requirement("RAP-3.06", "RAP", 3, None, "RAP-3.06", "low",
                "Turn on Windows Credential Guard",
                "Credential Guard functionality is enabled."),
    Requirement("RAP-3.07", "RAP", 3, None, "RAP-3.07", "low",
                "Turn on Windows Remote Credential Guard",
                "Remote Credential Guard functionality is enabled."),
    Requirement("RAP-3.08", "RAP", 3, None, "LOGS-INTERNAL-SERVERS", "high",
                "Review logs from internal servers promptly",
                "Event logs from non-internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("RAP-3.09", "RAP", 3, None, "LOGS-WORKSTATIONS", "high",
                "Review logs from staff computers promptly",
                "Event logs from workstations are analysed in a timely manner to detect cyber security events."),
    Requirement("AC-1.01", "AC", 1, None, "AC-1.01", "high",
                "Use application control on staff computers",
                "Application control is implemented on workstations."),
    Requirement("AC-1.02", "AC", 1, None, "AC-1.02", "medium",
                "Apply application control to user profile and temp folders",
                "Application control is applied to user profiles and temporary folders used by operating systems, web browsers and email clients."),
    Requirement("AC-1.03", "AC", 1, None, "AC-1.03", "high",
                "Only allow approved programs, scripts and installers to run",
                "Application control restricts the execution of executables, software libraries, scripts, installers, compiled HTML, HTML applications and control panel applets to an organisation-approved set."),
    Requirement("AC-2.01", "AC", 2, None, "AC-2.01", "high",
                "Use application control on internet-facing servers",
                "Application control is implemented on internet-facing servers."),
    Requirement("AC-2.02", "AC", 2, None, "AC-2.02", "medium",
                "Apply application control to all other folders too",
                "Application control is applied to all locations other than user profiles and temporary folders used by operating systems, web browsers and email clients."),
    Requirement("AC-2.03", "AC", 2, None, "AC-2.03", "low",
                "Apply Microsoft's recommended application blocklist",
                "Microsoft’s recommended application blocklist is implemented."),
    Requirement("AC-2.04", "AC", 2, None, "AC-2.04", "low",
                "Review application control rules at least yearly",
                "Application control rulesets are validated on an annual or more frequent basis."),
    Requirement("AC-2.05", "AC", 2, None, "AC-2.05", "medium",
                "Centrally log allowed and blocked application events",
                "Allowed and blocked application control events are centrally logged."),
    Requirement("AC-2.06", "AC", 2, None, "LOGS-PROTECTED", "medium",
                "Protect event logs from being changed or deleted",
                "Event logs are protected from unauthorised modification and deletion."),
    Requirement("AC-2.07", "AC", 2, None, "LOGS-INTERNET-SERVERS", "high",
                "Review logs from internet-facing servers promptly",
                "Event logs from internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("AC-2.08", "AC", 2, None, "EVENTS-TRIAGED", "high",
                "Check security events promptly to spot incidents",
                "Cyber security events are analysed in a timely manner to identify cyber security incidents."),
    Requirement("AC-2.09", "AC", 2, None, "INCIDENTS-TO-LEAD", "low",
                "Report incidents to your security lead straight away",
                "Cyber security incidents are reported to the chief information security officer, or one of their delegates, as soon as possible after they occur or are discovered."),
    Requirement("AC-2.10", "AC", 2, None, "INCIDENTS-TO-ASD", "low",
                "Report incidents to ASD (cyber.gov.au / 1300 CYBER1)",
                "Cyber security incidents are reported to ASD as soon as possible after they occur or are discovered."),
    Requirement("AC-2.11", "AC", 2, None, "IR-PLAN-ENACTED", "medium",
                "Follow your incident response plan when an incident happens",
                "Following the identification of a cyber security incident, the cyber security incident response plan is enacted."),
    Requirement("AC-3.01", "AC", 3, None, "AC-3.01", "high",
                "Use application control on internal servers",
                "Application control is implemented on non-internet-facing servers."),
    Requirement("AC-3.02", "AC", 3, None, "AC-3.02", "medium",
                "Only allow approved drivers to load",
                "Application control restricts the execution of drivers to an organisation-approved set."),
    Requirement("AC-3.03", "AC", 3, None, "AC-3.03", "low",
                "Apply Microsoft's vulnerable driver blocklist",
                "Microsoft’s vulnerable driver blocklist is implemented."),
    Requirement("AC-3.04", "AC", 3, None, "LOGS-INTERNAL-SERVERS", "high",
                "Review logs from internal servers promptly",
                "Event logs from non-internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("AC-3.05", "AC", 3, None, "LOGS-WORKSTATIONS", "high",
                "Review logs from staff computers promptly",
                "Event logs from workstations are analysed in a timely manner to detect cyber security events."),
    Requirement("MAC-1.01", "MAC", 1, None, "MAC-1.01", "low",
                "Disable Office macros for staff who don't need them",
                "Microsoft Office macros are disabled for users that do not have a demonstrated business requirement."),
    Requirement("MAC-1.02", "MAC", 1, None, "MAC-1.02", "low",
                "Block macros in Office files from the internet",
                "Microsoft Office macros in files originating from the internet are blocked."),
    Requirement("MAC-1.03", "MAC", 1, None, "MAC-1.03", "low",
                "Turn on antivirus scanning of Office macros",
                "Microsoft Office macro antivirus scanning is enabled."),
    Requirement("MAC-1.04", "MAC", 1, None, "MAC-1.04", "low",
                "Stop users changing Office macro security settings",
                "Microsoft Office macro security settings cannot be changed by users."),
    Requirement("MAC-2.01", "MAC", 2, None, "MAC-2.01", "low",
                "Block Office macros from making Win32 API calls",
                "Microsoft Office macros are blocked from making Win32 API calls."),
    Requirement("MAC-3.01", "MAC", 3, None, "MAC-3.01", "medium",
                "Only run macros that are sandboxed, in a Trusted Location or signed by a trusted publisher",
                "Only Microsoft Office macros running from within a sandboxed environment, a Trusted Location or that are digitally signed by a trusted publisher are allowed to execute."),
    Requirement("MAC-3.02", "MAC", 3, None, "MAC-3.02", "medium",
                "Check macros for malicious code before signing them or trusting their location",
                "Microsoft Office macros are checked to ensure they are free of malicious code before being digitally signed or placed within Trusted Locations."),
    Requirement("MAC-3.03", "MAC", 3, None, "MAC-3.03", "low",
                "Only the admins who vet macros can change Trusted Locations",
                "Only privileged users responsible for checking that Microsoft Office macros are free of malicious code can write to and modify content within Trusted Locations."),
    Requirement("MAC-3.04", "MAC", 3, None, "MAC-3.04", "low",
                "Stop users enabling macros signed by untrusted publishers",
                "Microsoft Office macros digitally signed by an untrusted publisher cannot be enabled via the Message Bar or Backstage View."),
    Requirement("MAC-3.05", "MAC", 3, None, "MAC-3.05", "low",
                "Stop users enabling macros without V3 signatures",
                "Microsoft Office macros digitally signed by signatures other than V3 signatures cannot be enabled via the Message Bar or Backstage View."),
    Requirement("MAC-3.06", "MAC", 3, None, "MAC-3.06", "low",
                "Review Office's trusted publishers at least yearly",
                "Microsoft Office’s list of trusted publishers is validated on an annual or more frequent basis."),
    Requirement("UAH-1.01", "UAH", 1, None, "UAH-1.01", "low",
                "Disable or remove Internet Explorer 11",
                "Internet Explorer 11 is disabled or removed."),
    Requirement("UAH-1.02", "UAH", 1, None, "UAH-1.02", "low",
                "Stop web browsers running Java from the internet",
                "Web browsers do not process Java from the internet."),
    Requirement("UAH-1.03", "UAH", 1, None, "UAH-1.03", "low",
                "Block web ads in browsers",
                "Web browsers do not process web advertisements from the internet."),
    Requirement("UAH-1.04", "UAH", 1, None, "UAH-1.04", "low",
                "Stop users changing browser security settings",
                "Web browser security settings cannot be changed by users."),
    Requirement("UAH-2.01", "UAH", 2, None, "UAH-2.01", "medium",
                "Harden web browsers using ASD and vendor guidance",
                "Web browsers are hardened using ASD and vendor hardening guidance, with the most restrictive guidance taking precedence when conflicts occur."),
    Requirement("UAH-2.02", "UAH", 2, None, "UAH-2.02", "low",
                "Block Office from creating child processes",
                "Microsoft Office is blocked from creating child processes."),
    Requirement("UAH-2.03", "UAH", 2, None, "UAH-2.03", "low",
                "Block Office from creating executable content",
                "Microsoft Office is blocked from creating executable content."),
    Requirement("UAH-2.04", "UAH", 2, None, "UAH-2.04", "low",
                "Block Office from injecting code into other processes",
                "Microsoft Office is blocked from injecting code into other processes."),
    Requirement("UAH-2.05", "UAH", 2, None, "UAH-2.05", "low",
                "Stop Office activating embedded OLE packages",
                "Microsoft Office is configured to prevent activation of Object Linking and Embedding packages."),
    Requirement("UAH-2.06", "UAH", 2, None, "UAH-2.06", "medium",
                "Harden Office using ASD and vendor guidance",
                "Office productivity suites are hardened using ASD and vendor hardening guidance, with the most restrictive guidance taking precedence when conflicts occur."),
    Requirement("UAH-2.07", "UAH", 2, None, "UAH-2.07", "low",
                "Stop users changing Office security settings",
                "Office productivity suite security settings cannot be changed by users."),
    Requirement("UAH-2.08", "UAH", 2, None, "UAH-2.08", "low",
                "Block PDF software from creating child processes",
                "PDF software is blocked from creating child processes."),
    Requirement("UAH-2.09", "UAH", 2, None, "UAH-2.09", "medium",
                "Harden PDF software using ASD and vendor guidance",
                "PDF software is hardened using ASD and vendor hardening guidance, with the most restrictive guidance taking precedence when conflicts occur."),
    Requirement("UAH-2.10", "UAH", 2, None, "UAH-2.10", "low",
                "Stop users changing PDF software security settings",
                "PDF software security settings cannot be changed by users."),
    Requirement("UAH-2.11", "UAH", 2, None, "UAH-2.11", "medium",
                "Centrally log PowerShell module, script block and transcription events",
                "PowerShell module logging, script block logging and transcription events are centrally logged."),
    Requirement("UAH-2.12", "UAH", 2, None, "UAH-2.12", "medium",
                "Centrally log command-line process creation",
                "Command line process creation events are centrally logged."),
    Requirement("UAH-2.13", "UAH", 2, None, "LOGS-PROTECTED", "medium",
                "Protect event logs from being changed or deleted",
                "Event logs are protected from unauthorised modification and deletion."),
    Requirement("UAH-2.14", "UAH", 2, None, "LOGS-INTERNET-SERVERS", "high",
                "Review logs from internet-facing servers promptly",
                "Event logs from internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("UAH-2.15", "UAH", 2, None, "EVENTS-TRIAGED", "high",
                "Check security events promptly to spot incidents",
                "Cyber security events are analysed in a timely manner to identify cyber security incidents."),
    Requirement("UAH-2.16", "UAH", 2, None, "INCIDENTS-TO-LEAD", "low",
                "Report incidents to your security lead straight away",
                "Cyber security incidents are reported to the chief information security officer, or one of their delegates, as soon as possible after they occur or are discovered."),
    Requirement("UAH-2.17", "UAH", 2, None, "INCIDENTS-TO-ASD", "low",
                "Report incidents to ASD (cyber.gov.au / 1300 CYBER1)",
                "Cyber security incidents are reported to ASD as soon as possible after they occur or are discovered."),
    Requirement("UAH-2.18", "UAH", 2, None, "IR-PLAN-ENACTED", "medium",
                "Follow your incident response plan when an incident happens",
                "Following the identification of a cyber security incident, the cyber security incident response plan is enacted."),
    Requirement("UAH-3.01", "UAH", 3, None, "UAH-3.01", "low",
                "Disable or remove .NET Framework 3.5",
                ".NET Framework 3.5 (includes .NET 2.0 and 3.0) is disabled or removed."),
    Requirement("UAH-3.02", "UAH", 3, None, "UAH-3.02", "low",
                "Disable or remove Windows PowerShell 2.0",
                "Windows PowerShell 2.0 is disabled or removed."),
    Requirement("UAH-3.03", "UAH", 3, None, "UAH-3.03", "medium",
                "Run PowerShell in Constrained Language Mode",
                "PowerShell is configured to use Constrained Language Mode."),
    Requirement("UAH-3.04", "UAH", 3, None, "LOGS-INTERNAL-SERVERS", "high",
                "Review logs from internal servers promptly",
                "Event logs from non-internet-facing servers are analysed in a timely manner to detect cyber security events."),
    Requirement("UAH-3.05", "UAH", 3, None, "LOGS-WORKSTATIONS", "high",
                "Review logs from staff computers promptly",
                "Event logs from workstations are analysed in a timely manner to detect cyber security events."),
    Requirement("BAK-1.01", "BAK", 1, None, "BAK-1.01", "medium",
                "Back up data, apps and settings as often as the business needs",
                "Backups of data, applications and settings are performed and retained in accordance with business criticality and business continuity requirements."),
    Requirement("BAK-1.02", "BAK", 1, None, "BAK-1.02", "medium",
                "Keep backups in sync so you can restore to one point in time",
                "Backups of data, applications and settings are synchronised to enable restoration to a common point in time."),
    Requirement("BAK-1.03", "BAK", 1, None, "BAK-1.03", "medium",
                "Store backups securely and resiliently (e.g. offline or immutable copy)",
                "Backups of data, applications and settings are retained in a secure and resilient manner."),
    Requirement("BAK-1.04", "BAK", 1, None, "BAK-1.04", "medium",
                "Test restoring from backups as part of disaster recovery exercises",
                "Restoration of data, applications and settings from backups to a common point in time is tested as part of disaster recovery exercises."),
    Requirement("BAK-1.05", "BAK", 1, None, "BAK-1.05", "low",
                "Stop normal accounts accessing other people's backups",
                "Unprivileged user accounts cannot access backups belonging to other user accounts."),
    Requirement("BAK-1.06", "BAK", 1, None, "BAK-1.06", "low",
                "Stop normal accounts changing or deleting backups",
                "Unprivileged user accounts are prevented from modifying and deleting backups."),
    Requirement("BAK-2.01", "BAK", 2, None, "BAK-2.01", "low",
                "Stop admin accounts (other than backup admins) accessing others' backups",
                "Privileged user accounts (excluding backup administrator accounts) cannot access backups belonging to other user accounts."),
    Requirement("BAK-2.02", "BAK", 2, None, "BAK-2.02", "medium",
                "Stop admin accounts (other than backup admins) changing or deleting backups",
                "Privileged user accounts (excluding backup administrator accounts) are prevented from modifying and deleting backups."),
    Requirement("BAK-3.01", "BAK", 3, None, "BAK-3.01", "medium",
                "Stop normal accounts accessing even their own backups",
                "Unprivileged user accounts cannot access their own backups."),
    Requirement("BAK-3.02", "BAK", 3, None, "BAK-3.02", "medium",
                "Stop admin accounts (other than backup admins) accessing their own backups",
                "Privileged user accounts (excluding backup administrator accounts) cannot access their own backups."),
    Requirement("BAK-3.03", "BAK", 3, None, "BAK-3.03", "high",
                "Stop even backup admins changing or deleting backups during retention",
                "Backup administrator accounts are prevented from modifying and deleting backups during their retention period."),
)

STRATEGY_BY_CODE = {s.code: s for s in STRATEGIES}
KEYS = {r.key for r in REQUIREMENTS}


def _check() -> None:
    ids = [r.id for r in REQUIREMENTS]
    assert len(ids) == len(set(ids)), "duplicate requirement id"
    by_key: dict[str, Requirement] = {}
    for r in REQUIREMENTS:
        assert r.strategy in STRATEGY_BY_CODE, r.id
        assert 1 <= r.level <= MAX_LEVEL and (r.until is None or r.level <= r.until < MAX_LEVEL), r.id
        assert r.effort in ("low", "medium", "high"), r.id
        assert len(r.key) <= 32, r.id
        first = by_key.setdefault(r.key, r)
        assert (first.text, first.title) == (r.text, r.title), f"{r.key}: shared key, different wording"
    assert sorted(s.priority for s in STRATEGIES) == list(range(1, len(STRATEGIES) + 1))


_check()
